# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: Component
metadata:
  name: "matrikkel-proxy"
  tags:
  - "public"
spec:
  type: service
  lifecycle: production
  owner: heimdall
  system: matrikkel
  providesApis:
  - "matrikkel-proxy-api"
---
apiVersion: "backstage.io/v1alpha1"
kind: API
metadata:
  name: matrikkel-proxy-api
spec:
  type: openapi
  owner: heimdall
  system: matrikkel
  lifecycle: production
