# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: Component
metadata:
  name: "matrikkel-proxy"
  description: Brukes til internruting mellom matrikkelens ulike applikasjoner på SKIP.
  tags:
  - "public"
spec:
  type: service
  lifecycle: production
  owner: heimdall
  system: matrikkel
