# Kun til bruk for lokal kjøring og testing

services:
  matrikkel-proxy:
    image: matrikkel-proxy-local:latest
    build:
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
      - "8085:8081"
