# Til testing lokalt, ruter all trafikk til maskinen som kjører docker sin localhost:8081 (hvor man f.eks. har matrikkelen kjørende)

ProxyPass / http://host.docker.internal:8081/
ProxyPassReverse / http://host.docker.internal:8081/
