name: Deploy to All Environments

on:
  push:
  workflow_dispatch:

env:
  CI: true
  TZ: Europe/Oslo
  SLACK_CHANNEL: C04SQEX2858
  DEV_CLUSTER_NAME: atkv3-dev-user-cluster
  DEV_KUBERNETES_PROJECT_ID: kubernetes-dev-94b9
  DEV_SERVICE_ACCOUNT: matrikkel-deploy@matrikkel-dev-fd36.iam.gserviceaccount.com
  DEV_WORKLOAD_IDENTITY_PROVIDER: projects/422604778482/locations/global/workloadIdentityPools/matrikkel-deploy-pool/providers/github-provider
  PROD_CLUSTER_NAME: atkv3-prod-user-cluster
  PROD_KUBERNETES_PROJECT_ID: kubernetes-prod-e4a2
  PROD_SERVICE_ACCOUNT: matrikkel-deploy@matrikkel-prod-91b2.iam.gserviceaccount.com
  PROD_WORKLOAD_IDENTITY_PROVIDER: projects/367207507054/locations/global/workloadIdentityPools/matrikkel-deploy-pool/providers/github-provider

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  version:
    name: Calculate Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version-string.outputs.version }}
      image: ${{ steps.version-string.outputs.image }}

    steps:
      - name: Generate version string
        id: version-string
        shell: bash
        run: |
          version="$(date -u '+%Y.%m.%d-%H.%M')-$(echo "${GITHUB_SHA}" | cut -c1-7)"
          echo "version=${version}" >> "$GITHUB_OUTPUT"
          echo "image=ghcr.io/kartverket/matrikkel-proxy:${version}" >> "$GITHUB_OUTPUT"

  package-image:
    name: Build and (conditionally) Push Docker Image
    runs-on: ubuntu-latest
    needs:
      - version
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        uses: docker/build-push-action@v6
        env:
          image: ${{ needs.version.outputs.image }}
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ env.image }}
      - name: Tag commit med artifaktversjon
        run: |
          git tag ${{ needs.version.outputs.version }}
          git push origin ${{ needs.version.outputs.version }}

  pharos:
    name: Run Pharos
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - version
      - package-image
    permissions:
      actions: read
      packages: read
      contents: read
      security-events: write
    steps:
      - name: "Run Pharos"
        uses: kartverket/pharos@599d3fe4af8bae19fbfda831662e90ee1c406ec2 # v0.6.3
        with:
          image_url: ${{ needs.version.outputs.image }}
          trivy: true
          tfsec: true
          disable_severity_check: true

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - version
      - package-image
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Deploy matrikkel-proxy to dev
        uses: kartverket/matrikkel-actions/apps-repo-deploy@main
        with:
          apps: |
            atkv3-dev:matrikkel-main:matrikkel-proxy:${{ needs.version.outputs.version }}
      - name: Verify deployment to dev
        uses: kartverket/matrikkel-actions/k8s-deployment-feedback@main
        with:
          cluster: ${{ env.DEV_CLUSTER_NAME }}
          apps: |
            matrikkel-main:matrikkelproxy:${{ needs.version.outputs.version }}
          kubernetes_project_id: ${{ env.DEV_KUBERNETES_PROJECT_ID }}
          service_account: ${{ env.DEV_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ env.DEV_WORKLOAD_IDENTITY_PROVIDER }}

  deploy-qa:
    name: Deploy to QA
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - version
      - package-image
      - deploy-dev
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Deploy matrikkel-proxy to QA environments
        uses: kartverket/matrikkel-actions/apps-repo-deploy@main
        with:
          apps: |
            atkv3-prod:matrikkel-betatest:matrikkel-proxy:${{ needs.version.outputs.version }}
            atkv3-prod:matrikkel-prodtest:matrikkel-proxy:${{ needs.version.outputs.version }}
      - name: Verify deployment to QA
        uses: kartverket/matrikkel-actions/k8s-deployment-feedback@main
        with:
          cluster: ${{ env.PROD_CLUSTER_NAME }}
          apps: |
            matrikkel-betatest:matrikkelproxy:${{ needs.version.outputs.version }}
            matrikkel-prodtest:matrikkelproxy:${{ needs.version.outputs.version }}
          kubernetes_project_id: ${{ env.PROD_KUBERNETES_PROJECT_ID }}
          service_account: ${{ env.PROD_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ env.PROD_WORKLOAD_IDENTITY_PROVIDER }}

  deploy-prod-notifier:
    name: Slack Notify; Deploy to Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - version
      - pharos
      - deploy-qa
    outputs:
      messageId: ${{ steps.slack_notify.outputs.messageId }}
    permissions:
      actions: read
      contents: read
      id-token: write
    steps:
      - name: Notify slack (Setup)
        id: slack_notify
        uses: kartverket/matrikkel-actions/slack-approval-notifier/setup-octo@main
        with:
          channel: ${{ env.SLACK_CHANNEL }}
          environment: 'produksjon'
          appDescriptor: atkv3-prod:matrikkel-main:matrikkel-proxy:${{ needs.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - version
      - deploy-prod-notifier
    environment:
      name: production
    permissions:
      actions: read
      contents: read
      id-token: write

    steps:
      - name: Notify slack (Update)
        uses: kartverket/matrikkel-actions/slack-approval-notifier/update-octo@main
        with:
          channel: ${{ env.SLACK_CHANNEL }}
          environment: 'produksjon'
          appDescriptor: atkv3-prod:matrikkel-main:matrikkel-proxy:${{ needs.version.outputs.version }}
          messageId: ${{ needs.deploy-prod-notifier.outputs.messageId }}
          status: ${{ job.status }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Deploy matrikkel-proxy to production
        uses: kartverket/matrikkel-actions/apps-repo-deploy@main
        with:
          apps: |
            atkv3-prod:matrikkel-main:matrikkel-proxy:${{ needs.version.outputs.version }}
            atkv3-prod:matrikkel-nd:matrikkel-proxy:${{ needs.version.outputs.version }}
            atkv3-prod:matrikkel-se-eiendom:matrikkel-proxy:${{ needs.version.outputs.version }}
      - name: Verify deployment to production
        if: false # Disabler sjekken her mens vi venter på at vi kan skru på auto-sync i argo
        uses: kartverket/matrikkel-actions/k8s-deployment-feedback@main
        with:
          cluster: ${{ env.PROD_CLUSTER_NAME }}
          apps: |
            matrikkel-main:matrikkelproxy:${{ needs.version.outputs.version }}
            matrikkel-nd:matrikkelproxy:${{ needs.version.outputs.version }}
            matrikkel-se-eiendom:matrikkelproxy:${{ needs.version.outputs.version }}
          kubernetes_project_id: ${{ env.PROD_KUBERNETES_PROJECT_ID }}
          service_account: ${{ env.PROD_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ env.PROD_WORKLOAD_IDENTITY_PROVIDER }}

  deploy-remaining-environments:
    name: Deploy to remaining environments
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - version
      - deploy-prod
    permissions:
      id-token: write

    steps:
      - name: Deploy matrikkel-proxy to remaining environments
        uses: kartverket/matrikkel-actions/apps-repo-deploy@main
        env:
          version: ${{ needs.version.outputs.version }}
        with:
          apps:
            atkv3-dev:matrikkel-releasetest:matrikkel-proxy:${{ env.version }}
            
            atkv3-prod:matrikkel-foringsenheten:matrikkel-proxy:${{ env.version }}
            atkv3-prod:matrikkel-kommunetest:matrikkel-proxy:${{ env.version }}
            
            atkv3-prod:matrikkel-kurs-1:matrikkel-proxy:${{ env.version }}
            atkv3-prod:matrikkel-kurs-2:matrikkel-proxy:${{ env.version }}
            atkv3-prod:matrikkel-kurs-3:matrikkel-proxy:${{ env.version }}
            atkv3-prod:matrikkel-kurs-norconsult:matrikkel-proxy:${{ env.version }}
            atkv3-prod:matrikkel-kurs-norkart:matrikkel-proxy:${{ env.version }}
            
            atkv3-prod:matrikkel-simtest:matrikkel-proxy:${{ env.version }}
            atkv3-prod:matrikkel-sitfor:matrikkel-proxy:${{ env.version }}